version: '3.1'
services:
  projeto_mvc:
    image: michelsp/php:fpm-8.3
    container_name: projeto_mvc_php
    volumes:
      - .:/var/www/webdev

  projeto_mvc_http:
    image: nginx:latest
    container_name: projeto_mvc_http
    environment:
      - HOSTNAME=projeto_mvc
      - VIRTUAL_HOST=projeto_mvc
      - VIRTUAL_PORT=8080
    volumes:
      - .:/var/www/webdev
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - projeto_mvc

  projeto_mvc_postgres:
    image: postgres:13
    restart: always
    container_name: projeto_mvc_postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"